### Sem3 Python 2023-24

In [7]:
def count(s):
    for str in s.split():
        s = "&".join(str)
    return s

print(count("Python is fun to learn."))

l&e&a&r&n&.


In [10]:
x = [12, 'hello', 456]
x[0] = '23'
x[1][2] = 'bye'

TypeError: 'str' object does not support item assignment

In [13]:
tup =(1,3,4)
x,y,z = tup
print(x," ",y," ",z)
x =x +2
print(x)

1   3   4
3


In [15]:
# q2 a 

# ii

lst = [2,3,4,5]
print(lst)

lst[1] = 30
print(lst)

[2, 3, 4, 5]
[2, 30, 4, 5]


In [16]:
#q2 a 

# iii

str1= "My"
str2 = "Name"
print(str1+" "+ str2)

My Name


In [1]:
# q2 c
L =[1,2,3,4,5,6,7,8,9]

print(L[:-1])

print(L[2:len(L)])
print(L[2:])

#only even positions
print(L[1::2]) 


# list that start from the middle of the list
print(L[len(L)//2 : ])

# 5. Reverse first half of list
middle = len(L) // 2
L[:middle] = L[:middle][::-1]
print(L)

#6 divide each elt of the list by 2 and replace it with remainder 
L = [x%2 for x in L]
print(L)

[1, 2, 3, 4, 5, 6, 7, 8]
[3, 4, 5, 6, 7, 8, 9]
[3, 4, 5, 6, 7, 8, 9]
[2, 4, 6, 8]
[5, 6, 7, 8, 9]
[4, 3, 2, 1, 5, 6, 7, 8, 9]
[0, 1, 0, 1, 1, 0, 1, 0, 1]


In [3]:
def perfect_square(number):
    if((number**0.5)**2  == number):
        return 1
    else:
        return -1
number = 15
print(perfect_square(number))

-1


In [13]:
# Step 1: Open and read the input file
with open("input.txt", "r") as file:
    data = file.read()
    print(data)

# Step 2: Place a comma after each character
output = ",".join(data)  # Adds a comma after every character

# Step 3: Write the processed content to the output file
with open("output.txt", "w") as file:
    file.write(output)

## Section C

In [1]:
#Q3 a

def removenth(s,n):
    if n>= len(s) & n <0:
        return s
    else:
        return s[:n]+s[n+1:]
print(removenth("Mango",1))

Mngo


In [4]:
#Q3 b
words = input("Enter the comma separated sequences of words:")
words = words.split(",")

sorted_words = ",".join(sorted(word.strip() for word in words))
print(sorted_words)

Enter the comma separated sequences of words: hello,my,name,is,what


hello,is,my,name,what


In [6]:
words = input("Enter the comma separated sequences of words:")
words = words.split(",")
words = sorted(words)
words = ",".join(words)
print(words)

Enter the comma separated sequences of words: hello,my,is,lakhan


hello,is,lakhan,my


In [11]:
import re

def is_valid_password(password):
    if((6<=len(password) <= 12) and
       re.search(r"[A-Z]",password) and
       re.search(r"[a-z]",password) and
       re.search(r"[0-9]",password) and
       re.search(r"[@#$]",password)):
        return True
    return False
valid_PassWords = []
passwords=input("Enter the sequence of comma separated passwords:")
passwords = passwords.split()
for password in passwords:
    password = password.strip()
    if is_valid_password:
        valid_PassWords.append(password)
result  = ",".join(valid_PassWords)
print(result)        

Enter the sequence of comma separated passwords: Smr@tunjay7,Vighnnesh0


Smr@tunjay7,Vighnnesh0


In [15]:
def ret_smaller(nested_list):
    return min(nested_list,key = len)
print(ret_smaller([[1,2,3],[21,3,54,2,64,2],[1,2324],["e","RFED","AFK"]]))

[1, 2324]


In [19]:
def print_digit_word(text):
    words = text.split()
    for word in words:
        if word.isdigit():
            print(word)
with open("input.txt","r") as f:
    data = f.read()
print_digit_word(data)
    

2
3
5


In [21]:
num = 68
print(chr(num))

D


In [23]:
import numpy as np
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:

numbers = [1, 2, 2, 3, 4, 4, 5]
unset=set(numbers)
unique_numbers = list(unset)
  

TypeError: 'list' object is not callable

In [30]:
l3=[23,43,2,534,2,4,3]
sum = 0
for i in l3:
    sum +=i
print(sum)

611


In [32]:
celsius = [0, 20, 30, 40]
fahrenheit = list(map(lambda c: (c * 9/5) + 32, celsius))
print(fahrenheit)

TypeError: 'list' object is not callable

In [33]:
with open("input.txt","r") as f:
    data = f.read()
with open("output.txt","w") as f:
    f.write(data.title())

In [34]:
import numpy as np
print(np.random.randint(10,50,size=5))

[20 14 47 18 42]


In [36]:
import pandas as pd
dataframe={
    "X1":[1,2,3,4],
    "X2":[2,4,6,8]    
}
df = pd.DataFrame(dataframe)
df.

X1  X2
0   1   2
1   2   4
2   3   6
3   4   8

In [14]:
cars=("BMW","Mercedes","Audi","Tata","Mahindra","Tesla")
car1,*car2,car3,car4=cars
print(car1)
print(car2)
print(car3)
print(car4)

BMW
['Mercedes', 'Audi', 'Tata']
Mahindra
Tesla
