In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

b.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [6]:
print(b.shape)
print(b.dtype)


(3, 3)
int64


In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
#specific  element in the array [r,c] 
a[1,1]

9

In [21]:
#Get a specific row  [r, ]

print(a[1,:])


[ 8  9 10 11 12 13 14]
