In [26]:
import numpy as np

In [27]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [28]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

b.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [29]:
print(b.shape)
print(b.dtype)


(3, 3)
int64


In [30]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [31]:
#specific  element in the array [r,c] 
a[1,1]

9

In [32]:
#Get a specific row  [r, ]

print(a[1,:])


[ 8  9 10 11 12 13 14]


In [33]:
# Get a  specific colomn [ ,c]
a[: ,4]

array([ 5, 12])

In [34]:
a[1,1] = 90
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8 90 10 11 12 13 14]]


###Intializing the Different Types of Arrray

In [40]:
# All 0s Array
a = np.zeros((3,4,4),int)
a 

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [54]:
# All Ones Matrix

b= np.ones((3,3),dtype="int32")
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [57]:
 #Any other Number

c = np.full((3,4),45,dtype="int16")
c

array([[45, 45, 45, 45],
       [45, 45, 45, 45],
       [45, 45, 45, 45]], dtype=int16)

In [58]:
# Any other NUmber (full-like)
d = np.full_like(c,34)
d

array([[34, 34, 34, 34],
       [34, 34, 34, 34],
       [34, 34, 34, 34]], dtype=int16)

In [66]:
#Random Decimal Variable
np.random.rand(3,3)

array([[0.7395553 , 0.33893141, 0.61999614],
       [0.77581144, 0.68235708, 0.42494169],
       [0.87562586, 0.54616874, 0.01559879]])

In [69]:
np.random.random_sample(a.shape)

array([[[0.80678638, 0.3918756 , 0.84918052, 0.747402  ],
        [0.56793318, 0.16927073, 0.29405394, 0.39363601],
        [0.89781418, 0.79123533, 0.38143191, 0.75244731],
        [0.0692855 , 0.12984965, 0.22060599, 0.62560196]],

       [[0.32130552, 0.17659343, 0.58897786, 0.70778957],
        [0.29738715, 0.40239113, 0.36817658, 0.20972247],
        [0.32257075, 0.56397879, 0.59408397, 0.94233077],
        [0.02250263, 0.34550838, 0.69466433, 0.98670781]],

       [[0.85737736, 0.90038593, 0.78223622, 0.09596602],
        [0.40140594, 0.0799397 , 0.41781746, 0.74201998],
        [0.51679743, 0.95500452, 0.51565835, 0.38607882],
        [0.8272301 , 0.07110499, 0.2155918 , 0.52565508]]])

In [87]:
#Random Integers Value
random_array = np.random.randint(10,50,size=[3,3])
random_array


array([[25, 36, 39],
       [42, 11, 28],
       [33, 48, 40]])

In [89]:
#The Identity Matrix
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
output = np.ones([5,5])
print(output )

x = np.zeros([3,3])
print(x)

x[1][1] = 9
print(x)

output[1:-1,1:-1] = x
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [100]:
first = np.array([2,3,4])
second = first #here second is pointing to the same location where  the first is pointing 
second[0] = 34

print(first)
print(second)

[34  3  4]
[34  3  4]


In [101]:
second = first.copy()
second[0] = 45
print(first)
print(second)

[34  3  4]
[45  3  4]


#Mathmatics in Numpy arrays 

In [102]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [103]:
a+2


array([3, 4, 5, 6, 7])

In [104]:
a-2

array([-1,  0,  1,  2,  3])

In [105]:
a*4

array([ 4,  8, 12, 16, 20])

In [106]:
a / 4

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [108]:
b = np.array([0,1,0,1,0])
a + b 

array([1, 3, 3, 5, 5])

In [109]:
a ** 2

array([ 1,  4,  9, 16, 25])

# Linear algebra


In [119]:
a = np.ones((2,3),int)
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [122]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics
