In [26]:
import numpy as np

In [27]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [28]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

b.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [29]:
print(b.shape)
print(b.dtype)


(3, 3)
int64


In [30]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [31]:
#specific  element in the array [r,c] 
a[1,1]

9

In [32]:
#Get a specific row  [r, ]

print(a[1,:])


[ 8  9 10 11 12 13 14]


In [33]:
# Get a  specific colomn [ ,c]
a[: ,4]

array([ 5, 12])

In [34]:
a[1,1] = 90
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8 90 10 11 12 13 14]]


###Intializing the Different Types of Arrray

In [38]:
# All 0s Array
a = np.zeros((3,4),int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])